version: '3'

services:

  laser:
    image: laser
    ports:
      - 80
    environment:
      - SERVICE_PORTS=80
    networks:
      - web
    command: ["python", "app.py"]
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10m10s
      restart_policy:
        condition: on-failure

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - laser
    environment:
      - BALANCE=leastconn
    ports:
      - 8086:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay